fix: remove non-existent -y flag on walker
Walker does not support the `-y` flag.
Using `-n` (to hide input) causes a runtime error:

    Error during app execution: Failed to connect to new network: ignacio's A36
    Caused by:
        net.connman.iwd.InvalidFormat: Argument format is invalid
    Error: Fatal error in application: Failed to connect to new network: ignacio's A36

To restore basic connection functionality, this commit removes the `-y` flag.
This favors a working connection over hidden input until a proper solution can be found.

Closes: https://github.com/e-tho/iwmenu/issues/21
Signed-off-by: ignamartinoli@proton.me <ignamartinoli@protonmail.com>